# WEB SCRAPING – ASSIGNMENT 4

Read all the problem statements, notes carefully and scrape the required data using any web scraping tool of your choice.
 You have to handle commonly occurring EXCEPTIONS by using exception handling programing. To get information about selenium Exceptions. You may visit following links:
1. https://selenium-python.readthedocs.io/api.html
2. https://www.guru99.com/exception-handling-selenium.html
3. https://stackoverflow.com/questions/38022658/selenium-python-handling-no-such-element-exception/38023345

# 1. Scrape the details of most viewed videos on YouTube from Wikipedia:
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/ You need to find following details: A) Rank B) Name C) Artist D) Upload date E) Views

In [1]:
import selenium
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

In [2]:
driver=webdriver.Chrome(r"C:\Rajashri\Iternship\Chromdriver\chromedriver.exe")
time.sleep(3)
url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)

In [3]:
count = 0
#creating list for rank, uploader name, video name, no of views, date of upload
Rank = []
video_names = []
Artist = []
views = []
upload_dates = []
    #RANK ELEMENT
try:
    rank_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')[:30]
    for i in rank_obj:
        Rank.append(i.text)
except NoSuchElementException :
    Rank.append('-')
   #VIDEO NAME ELEMENT
try:
    videoname_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')[:30]
    for i in videoname_obj:
        video_names.append(i.text.split('[')[0][1:-1]) #extract only name from text remove []
except NoSuchElementException :
    video_names.append('-')

    #UPLOADER_OF_VIDEO
try:
    Artist1 = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')[:30]
    for i in Artist1:
        Artist.append(i.text)
except NoSuchElementException :
    Artist.append('-')

    #VIEWS ON THE VIDEOS
try:
    view_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')[:30]
    for i in view_obj:
        views.append(i.text)
except NoSuchElementException :
    views.append('-')
        
    #DATE OF THE VIDEO ELEMENT
try:
    date_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')[:30]
    for i in date_obj:
        upload_dates.append(i.text)
except NoSuchElementException :
    upload_dates.append('-')
    
# creating a diction of all the columns
dict = {'rank':Rank, 'video_name':video_names,'Artist':Artist,'Upload date':upload_dates,'Views(Billions)':views}
# CREATING TABLE / dATA fRAME OF THE DICTIONARY
Data = pd.DataFrame(dict)
Data

,rank,video_name,Artist,Upload date,Views(Billions)
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",9.44
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.57
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",5.77
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.48
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.28
5,6.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",4.55
6,7.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.52
7,8.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.46
8,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.32
9,10.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.22
10,11.,Gangnam Style,Psy,"July 15, 2012",4.21
11,12.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.63
12,13.,Sugar,Maroon 5,"January 14, 2015",3.56
13,14.,Sorry,Justin Bieber,"October 22, 2015",3.47
14,15.,Roar,Katy Perry,"September 5, 2013",3.44
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.41
16,17.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.34
17,18.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.29
18,19.,Dark Horse,Katy Perry,"February 20, 2014",3.15
19,20.,Faded,Alan Walker,"December 3, 2015",3.15
20,21.,Girls Like You,Maroon 5,"May 31, 2018",3.14
21,22.,Lean On,Major Lazer,"March 22, 2015",3.10
22,23.,Bailando,Enrique Iglesias,"April 11, 2014",3.10
23,24.,Shake It Off,Taylor Swift,"August 18, 2014",3.10
24,25.,Let Her Go,Passenger,"July 25, 2012",3.09
25,26.,Axel F,Crazy Frog,"June 16, 2009",3.03
26,27.,Mi Gente,J Balvin,"June 29, 2017",2.99
27,28.,Perfect,Ed Sheeran,"November 9, 2017",2.97
28,29.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",2.96
29,30.,Hello,Adele,"October 22, 2015",2.89

# 2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [4]:
driver=webdriver.Chrome(r"C:\Rajashri\Iternship\Chromdriver\chromedriver.exe")
url = 'https://www.bcci.tv/'
driver.get(url)

In [5]:
internation_fixtures_obj = driver.find_element_by_xpath('/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]/div/ul/li[1]/a')
# dorpdown element international fixtures.
link = internation_fixtures_obj.get_attribute('href')
driver.get(link)

In [6]:
date = []
time = []
series = []
place = []
match_title = []
match_details = []
# combine Month and Day for Date list
try :
    month_obj = driver.find_elements_by_xpath('//span[@class="fixture__month"]')
    day_obj = driver.find_elements_by_xpath('//span[@class="fixture__date"]')
    for i in range(len(month_obj)):
        date.append(str(day_obj[i].text)+' '+str(month_obj[i].text).lower())
except NoSuchElementException:
    date.append('-')
    
# Time of match  
try :
    time_obj = driver.find_elements_by_xpath('//span[@class="fixture__time"]')
    
    for i in range(len(time_obj)):
        time.append(str(time_obj[i].text))
except NoSuchElementException:
    time.append('-')

#series details and Match Tittle

try :
    series_obj = driver.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__format"]')
    title_obj = driver.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__tournament-label u-truncated"]')
    for i in range(len(month_obj)):
        series.append(str(series_obj[i].text)+' '+str(title_obj[i].text))
        match_title.append(str(title_obj[i].text))
except NoSuchElementException:
    series.append('-')

    
# Location of MAtch, and series information
try :
    location_obj = driver.find_elements_by_xpath('//p[@class="fixture__additional-info"]/span')
    match_name_obj = driver.find_elements_by_xpath('//strong[@class="fixture__name fixture__name--with-margin"]')
    for i in range(len(time_obj)):
        place.append(str(location_obj[i].text))
        match_details.append(match_name_obj[i].text)
except NoSuchElementException:
    place.append ('-')

#creating the dictionary of the elements
dict= {
    'Match Title': match_title,'Series':series,'Match Location':place,'Date':date,'Time':time,
    'series details': match_details
}

#Fixtures creating with creating a DataFrame
Fixtures = pd.DataFrame(dict)
Fixtures

,Match Title,Series,Match Location,Date,Time,series details
0,2021 ICC MEN'S T20 WORLD CUP,T20I 2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",24 october,19:30 IST,Match 16
1,2021 ICC MEN'S T20 WORLD CUP,T20I 2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",31 october,19:30 IST,Match 28
2,2021 ICC MEN'S T20 WORLD CUP,T20I 2021 ICC MEN'S T20 WORLD CUP,"Zayed Cricket Stadium, Abu Dhabi",03 november,19:30 IST,Match 33
3,2021 ICC MEN'S T20 WORLD CUP,T20I 2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",05 november,19:30 IST,Match 37
4,2021 ICC MEN'S T20 WORLD CUP,T20I 2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",08 november,19:30 IST,Match 42
5,INDIA V NEW ZEALAND 2021,T20I INDIA V NEW ZEALAND 2021,"Sawai Mansingh Stadium, Jaipur",17 november,19:00 IST,1st T20I
6,INDIA V NEW ZEALAND 2021,T20I INDIA V NEW ZEALAND 2021,"JSCA International Stadium Complex, Ranchi",19 november,19:00 IST,2nd T20I
7,INDIA V NEW ZEALAND 2021,T20I INDIA V NEW ZEALAND 2021,"Eden Gardens, Kolkata",21 november,19:00 IST,3rd T20I
8,INDIA V NEW ZEALAND 2021,TEST INDIA V NEW ZEALAND 2021,"Green Park, Kanpur",25 november,09:30 IST,1st Test
9,INDIA V NEW ZEALAND 2021,TEST INDIA V NEW ZEALAND 2021,"Wankhede Stadium, Mumbai",03 december,09:30 IST,2nd Test
10,SOUTH AFRICA V INDIA 2021/2022,TEST SOUTH AFRICA V INDIA 2021/2022,"New Wanderers Stadium, Johannesburg",17 december,13:30 IST,1st Test
11,SOUTH AFRICA V INDIA 2021/2022,TEST SOUTH AFRICA V INDIA 2021/2022,"Supersport Park, Centurion",26 december,13:30 IST,2nd Test
12,SOUTH AFRICA V INDIA 2021/2022,TEST SOUTH AFRICA V INDIA 2021/2022,"New Wanderers Stadium, Johannesburg",03 january,13:30 IST,3rd Test
13,SOUTH AFRICA V INDIA 2021/2022,ODI SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",11 january,14:00 IST,1st ODI
14,SOUTH AFRICA V INDIA 2021/2022,ODI SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",14 january,14:00 IST,2nd ODI
15,SOUTH AFRICA V INDIA 2021/2022,ODI SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",16 january,14:00 IST,3rd ODI
16,SOUTH AFRICA V INDIA 2021/2022,T20I SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",19 january,19:30 IST,1st T20I
17,SOUTH AFRICA V INDIA 2021/2022,T20I SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",21 january,19:30 IST,2nd T20I
18,SOUTH AFRICA V INDIA 2021/2022,T20I SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",23 january,19:30 IST,3rd T20I
19,SOUTH AFRICA V INDIA 2021/2022,T20I SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",26 january,19:30 IST,4th T20I

# 3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [9]:
driver=webdriver.Chrome(r"C:\Rajashri\Iternship\Chromdriver\chromedriver.exe")
url = 'https://www.guru99.com/'
driver.get(url)
#clicking on Selenium tutorial
driver.find_element_by_xpath("//div[@class='srch']/span[8]/a").click()
# finding the link of Selenium Common Exceptions list and gettting its url and loading it to the web browser
exception_link = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a")
driver.get(exception_link.get_attribute('href'))
# All datas are available in table format , no missing vlaues to cause exceptions.
row_obj = driver.find_elements_by_xpath('//table[@class="table table-striped"]')

In [10]:
name = []
description = []
table =driver.find_elements_by_xpath('//table[@class="table table-striped"]//tr//td[1]')
desc =driver.find_elements_by_xpath('//table[@class="table table-striped"]//tr//td[2]')

for i in table:
    name.append(i.text)
for j in desc:
    description.append(j.text)
exceptions = pd.DataFrame({})
exceptions['Exception name'] = name[1:]
exceptions['Exception Description'] =description[1:]
exceptions

,Exception name,Exception Description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP at current price (19-20)
D) GSDP at current price (18-19)
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [11]:
driver=webdriver.Chrome(r"C:\Rajashri\Iternship\Chromdriver\chromedriver.exe")
url = 'http://statisticstimes.com/'
driver.get(url)

In [12]:
#finding the link of Economy of India
india_economy_page = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
#extracting the url from the element
link  = india_economy_page.get_attribute('href')
#giving the india economy url to the browser
driver.get(link)
#Click the State-wise gdp of india element
driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()

In [13]:
ranks = []
states = []
GSDP_current_price_19_20 = []
GSDP_current_price_18_19 = []
share_18_19 = []
gdp_19 = []

    #Rank Element

try:
    rank_element = driver.find_elements_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr/td[1]')
    for i in rank_element:
        ranks.append(i.text)
except NoSuchElementException:
    ranks.append('-')
    
    #State Element

try:
    state_element = driver.find_elements_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr/td[2]')
    for i in state_element:
        states.append(i.text)
except NoSuchElementException:
    states.append('-')
   
    
    #GSDP 19-20 element

try:
    GSDP_19_20_element = driver.find_elements_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr/td[3]')
    for i in GSDP_19_20_element:
        GSDP_current_price_19_20.append(i.text)
except NoSuchElementException:
    GSDP_current_price_19_20.append('-')
    
     #GSDP 18-19 element
    
try:
    GSDP_18_19_element = driver.find_elements_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr/td[4]')
    for i in GSDP_18_19_element:
        GSDP_current_price_18_19.append(i.text)
except NoSuchElementException:
    GSDP_current_price_18_19.append('-')
    
    
    #share element for 18-19
    
try:
    share_element = driver.find_elements_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr/td[5]')
    for i in share_element:
        share_18_19.append(i.text)
except NoSuchElementException:
    share_18_19.append('-')
    
    
    #GDP of 2019
    
try:
    GDP_element = driver.find_elements_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr/td[6]')
    for i in GDP_element:
        gdp_19.append(i.text)
except NoSuchElementException:
    gdp_19.append('-')

In [14]:
#Creating a Dictionarty of the all the elements
dict = {
    'Rank':ranks, 'State Name':states,'GSDP_current_price_19_20': GSDP_current_price_19_20,'GSDP_current_price_18_19':GSDP_current_price_18_19,
    'Share_18_19':share_18_19,'GDP($ billion)':gdp_19
    }

#loading the dictionary to a dataframe 
table = pd.DataFrame(dict)
table

,Rank,State Name,GSDP_current_price_19_20,GSDP_current_price_18_19,Share_18_19,GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# 5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used# 
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [15]:
driver=webdriver.Chrome(r"C:\Rajashri\Iternship\Chromdriver\chromedriver.exe")
url = 'https://github.com/'
driver.get(url)
#find the element of the Trending from the dropdown of the EXPLORE column and extracting the URL of trending

link_trending = driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a').get_attribute('href')
link_trending

'https://github.com/trending'

In [16]:
#feeding the trending url to the browser

driver.get(link_trending)
repo_titles = []

repo_urls = []

#Extraction Repository Name and its corresponding urls
title_element = driver.find_elements_by_xpath('//*[@id="js-pjax-container"]/div[3]/div/div[2]/article/h1/a')
for i in title_element:
    repo_urls.append(i.get_attribute('href'))
    repo_titles.append(i.text)

In [17]:
repo_descriptions = []
contributors_counts = []
language_used  = []

#LOOPING THROUGH THE REPOSITORY URLS TO EXTRACT DATA FROM EACH LINK>

for  i in repo_urls:
    
    #loading the repositroy link to the browsetr
    driver.get(i)
    #waitng for the browser to load and keep the browser to sleep mode for 2 sec
    #DESCRIPTION OF REPOSITORY
    try :
        description_element = driver.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]/div/div[1]/div/p')
        
        repo_descriptions.append(description_element.text)
    except NoSuchElementException:
        repo_descriptions.append('-')

    #CONTRIBUTORS_cOUNT
    try :
        contributors_element = driver.find_element_by_xpath('/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[5]/div/h2/a/span')
       
        contributors_counts.append(contributors_element.text)
    except NoSuchElementException:
        contributors_counts.append('-')

    #LANGUAGES used

    try :
        language_element = driver.find_elements_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/a')
        li = []
        for i in language_element:
           
            li.append(i.text)
        language_used.append(', '.join(li))
    except NoSuchElementException:
        language_used.append('-')

#creating a dictionary of all the elements
dict={
    'Repository Title': repo_titles,
    'Repository Description':repo_descriptions,
    'Contributors Count': contributors_counts,
    'Languages Used': language_used,

}

table = pd.DataFrame(dict)
table

,Repository Title,Repository Description,Contributors Count,Languages Used
0,peng-zhihui / Dummy-Robot,我的超迷你机械臂机器人项目。,-,
1,trailofbits / algo,Set up a personal VPN in the cloud,156,
2,Snailclimb / JavaGuide,「Java学习+面试指南」一份涵盖大部分 Java 程序员所需要掌握的核心知识。准备 Jav...,261,
3,louislam / uptime-kuma,A fancy self-hosted monitoring tool,-,"docker, monitoring, responsive, single-page-ap..."
4,vuejs / vue-next,"🖖 Vue.js is a progressive, incrementally-adopt...",64,
5,babysor / MockingBird,🚀AI拟声: 5秒内克隆您的声音并生成任意语音内容 Clone a voice in 5 s...,-,"ai, deep-learning, speech, pytorch"
6,facebook / flipper,A desktop debugging platform for mobile develo...,219,
7,fatedier / frp,A fast reverse proxy to help you expose a loca...,14,"go, tunnel, proxy, firewall, nat, http-proxy, ..."
8,ossrs / srs,"SRS is a simple, high efficiency and realtime ...",-,
9,vinta / awesome-python,"A curated list of awesome Python frameworks, l...",-,
10,yt-dlp / yt-dlp,A youtube-dl fork with additional features and...,854,
11,ihciah / clean-dns-bpf,基于 Rust + eBPF 丢弃 GFW DNS 污染包,-,
12,sdras / awesome-actions,A curated list of awesome actions to use on Gi...,-,"github, awesome, actions, awesome-list, curate..."
13,Hack-with-Github / Awesome-Hacking,A collection of various awesome lists for hack...,-,"android, security, awesome, reverse-engineerin..."
14,anncwb / vue-vben-admin,"A modern vue admin. It is based on Vue3, vite ...",72,
15,Python-World / Python_and_the_Web,"Build Bots, Scrape a website or use an API to ...",-,"python, api, fun, bots, scraping-websites"
16,wimpysworld / quickemu,"Quickly create and run optimised Windows, macO...",16,
17,mattiasgustavsson / dos-like,"Engine for making things with a MS-DOS feel, b...",-,
18,apache / rocketmq,Mirror of Apache RocketMQ,280,rocketmq
19,donet5 / WebFirst,.NET CORE 代码生成器 ，Web中使用CodeFirst模式， 实体生成器，UI代码...,-,
20,raywenderlich / flta-materials,The projects and the materials that accompany ...,8,
21,herosi / CTO,Call Tree Overviewer,-,
22,alibaba / Sentinel,A powerful flow control component enabling rel...,152,
23,alibaba / spring-cloud-alibaba,Spring Cloud Alibaba provides a one-stop solut...,114,
24,vuejs / vue,"🖖 Vue.js is a progressive, incrementally-adopt...",401,

# 6. Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [18]:
driver=webdriver.Chrome(r"C:\Rajashri\Iternship\Chromdriver\chromedriver.exe")
url = 'https://www.billboard.com/'
driver.get(url)
link = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/header/div/ul/li[1]/span/span/span/span[1]/ul/li[1]/a').get_attribute('href')

In [19]:
#loading the extracted link of the hot top 100
driver.get(link)
song = []
artist = []
last_week_rank = []
peak_rank = []
weeks_on_board = []

#SONG NAME ELEMENT EXTRACTION
try:
    song_name_obj = driver.find_elements_by_xpath('//span[@class="chart-element__information"]/span[1]')
   
    for i in range(len(song_name_obj)):
        song.append(song_name_obj[i].text)
except NoSuchElementException:
    song.append('-')
    
    
#ARTIST NAME ELEMENT EXTRACTION
try:
   
    singer_name_obj = driver.find_elements_by_xpath('//span[@class="chart-element__information"]/span[2]')
    for i in range(len(singer_name_obj)):
        
        artist.append(singer_name_obj[i].text)
except NoSuchElementException:
    artist.append('-')
    
    
#LAST WEEK RANK of a SONG  ELEMENT EXTRACTION    
    #chart-element__metas chart-element__metas--large display--flex flex--y-center
try:
    rank_lastweek_obj = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--last"]')
   
    for i in range(len(rank_lastweek_obj)):
        last_week_rank.append(rank_lastweek_obj[i].text)
except NoSuchElementException:
    last_week_rank.append('-')
    
    
#PEAK RANK OF A SONG ELEMENT EXTRACTION    
try:
   
    peak_rank_obj = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--peak"]')
    for i in range(len(peak_rank_obj)):
        
        peak_rank.append(peak_rank_obj[i].text)
except NoSuchElementException:
     peak_rank.append('-')  
        
        
#WEEKS ON BOARD for a SONG ELEMENT EXTRACTION
try:
   
    no_of_weeks_onboard_obj = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--week"]')
    for i in range(len(no_of_weeks_onboard_obj)):
        
        weeks_on_board.append(no_of_weeks_onboard_obj[i].text)
except NoSuchElementException:
    weeks_on_board.append('-')

In [20]:
dict = {
    'Song Name': song, 'Artist Name':artist,
    'Last week Rank': last_week_rank,'Peak Rank':peak_rank,'Weeks on Board': weeks_on_board
}
table = pd.DataFrame(dict)
table

,Song Name,Artist Name,Last week Rank,Peak Rank,Weeks on Board
0,My Universe,Coldplay x BTS,-,1,1
1,Stay,The Kid LAROI & Justin Bieber,1,1,12
2,Industry Baby,Lil Nas X & Jack Harlow,2,2,10
3,Way 2 Sexy,Drake Featuring Future & Young Thug,3,1,4
4,Fancy Like,Walker Hayes,5,5,15
...,...,...,...,...,...
95,Pipe Down,Drake,68,14,4
96,Papi's Home,Drake,66,8,4
97,Chosen,Blxst & Tyga Featuring Ty Dolla $ign,-,98,1
98,Toxic Punk,YoungBoy Never Broke Again,-,99,1
99,Moon,Kanye West,76,17,5

# 7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code#

In [21]:
driver=webdriver.Chrome(r"C:\Rajashri\Iternship\Chromdriver\chromedriver.exe")
url = 'https://naukri.com'
driver.get(url)
#recruitor page link element
recruiter_link = driver.find_element_by_xpath('/html/body/div[1]/div[1]/div/ul[1]/li[2]/a').get_attribute('href')
#loading the recruitor link to the browser
driver.get(recruiter_link)
driver.current_url

'https://www.naukri.com/hr-recruiters-consultants'

In [22]:
#element of Search tab and seARCH button
input_tab = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
search_btn = driver.find_element_by_xpath('//button[@class="fl qsbSrch blueBtn"]')
#sending keys to the Search Tab
input_tab.send_keys('Data Science')

#click the  search element
search_btn.click()
#extracting the link elements of the recruitors
recruiter_name = driver.find_elements_by_xpath("//p[@class='highlightable']/a[1]")
#Links of all the companies
all_recruitment_links = []
for i in recruiter_name:
    all_recruitment_links.append(i.get_attribute('href'))

In [23]:
re_names= []
re_company = []
re_location = []
re_skills = []
re_designation = []
#lopping through each company to extract data of each company seperately.
for i in range(50):
    driver.get(all_recruitment_links[i])
   
    
    #Recruiter Name
    try:
        name_element = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[1]/div[2]/div[2]/h1')
        re_names.append(name_element.text)
    except NoSuchElementException:
        re_names.append('-')
        
    #Company NAme
    try:
        company_element = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div[2]/p[1]')
        re_company.append(company_element.text)
    except NoSuchElementException:
        re_company.append('-')
    
    #Location element
    try:
        location_element = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[1]/div[2]/div[5]/a')
       # for i in location_element:
        re_location.append(location_element.text)
    except NoSuchElementException:
        re_location.append('-')
        
    #Skills
    try:
        skills_element = driver.find_elements_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div[1]/p')
        li = []
        for i in skills_element:
            li.append(i.text)
            
        temp = ' '.join(li) 
        re_skills.append(temp)
        
    except NoSuchElementException:
        re_skills.append('-')
      
    
    #Designation element
    try:
        designation_element = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[1]/div[2]/div[3]')
        re_designation.append(designation_element.text)
    except NoSuchElementException:
        re_designation.append('-')

In [24]:
#creating a dictionary of all the elements
dict = {
    'Recruiter Name': re_names,'Recruiter_Designation':re_designation,'Recruiter_Company':re_company,
    'Skills for hiring':re_skills,
    'Location':re_location
}
#creating a DataFrame/ Table of the dictionary
table = pd.DataFrame(dict)
table

,Recruiter Name,Recruiter_Designation,Recruiter_Company,Skills for hiring,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer , Internet Marketing Pro...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd (Since Dec-2016),".Net , Java , Data Science , Linux Administrat...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP (Since Feb-2016),"Mid Level, Junior Level",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,", Mean Stack , javascript , angularjs , mongod...",Ahmedabad
4,Narasimha,Company Recruiter,-,Step Next Private Limited,Hyderabad / Secunderabad
5,subhas patel,Founder & CEO,LibraryXProject,"Hadoop , Spark , Digital Strategy , Data Archi...",UK - (london)
6,Abhishek - Only Analytics Hiring - India and APAC,Recruitment - Lead Consultant,Apidel Technologies Division of Transpower (Si...,"Analytics , Business Intelligence , Business A...",Vadodara / Baroda
7,Institute for Financial Management and Research,Programme Manager,IFMR (Since May-2017),Analytics & Business Intelligence,Chennai
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd (Since Dec-2014),"Machine Learning , algorithms , Go Getter , Co...",Trivandrum
9,Asif Lucknowi,Director,-,Weupskill- Live Wire India,Indore
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Junior Level, Mid Level",Bengaluru / Bangalore
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions Pvt.Ltd.,"Mid Level, High Level",Hyderabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software (Since Feb-2015),"Qa , Ui , ux , Java Developer , Java Architect...",Hyderabad / Secunderabad
13,Mubarak,Company HR,-,MoneyTap,Bengaluru / Bangalore
14,Kushal Rastogi,Company HR,-,QuantMagnum Technologies Pvt. Ltd.,Mumbai
15,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd (Since Apr-2021),IT Skills,Pune
16,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com (Since Jan-2014),"Junior Level, Mid Level",Hyderabad / Secunderabad
17,Kapil Devang,HR Manager,BISP Solutions,"Big Data , Hadoop , Data Analytics , Data Science",Bhopal
18,Manisha Yadav,HR Executive,Easi Tax,Mid Level,Navi Mumbai
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions (Since May-2019),IT-Software/Software Services,Cochin
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE LIMITED,"Mid Level, Top Mangement Level",Delhi
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics , Data Science , Machine Learni...",Hyderabad / Secunderabad
22,Rithika dadwal,HR Recruiter,Affine Analytics,"Junior Level, Mid Level",Pune
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"High Level, Mid Level",Pune
24,Shaun Rao,Manager - Human Resources,Exela Technologies (Since Nov-2014),"Java , Net , Angularjs , Hr , Infrastructure ,...",Pune
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Mid Level, High Level",Pune
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private Limited,"High Level, Top Mangement Level",Bengaluru / Bangalore
27,kumar,Proprietor,trainin,"Data Science , Hadoop , Rpas , Devops , Python...",Bengaluru / Bangalore
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing , Machine Learning , Neural ...",Others
29,Rajat Kumar,Founder & CEO,R.S Consultancy & Services,"Web Technologies , Project Management , Softwa...",Delhi
30,Priya Khare,Senior Manager,-,Independent Consultant,Bengaluru / Bangalore
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential (Since Jun-2016),"S. Finance Manager , Freshers , Experience , S...",Bengaluru / Bangalore
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd (Sinc...","Data Analytics , Managed Services , Team Leading",Mysoru / Mysore
33,SREEDHAR,Recruitment Consultant,-,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad
34,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,"Mid Level, Top Mangement Level",Ghaziabad
35,Radha Manivasagam,HR Executive,Techcovery,Junior Level,Bengaluru / Bangalore
36,Prateek Kumar,Head,Trisect (Since Jan-2013),Junior Level,Noida
37,Amit Sharma,Consultant,-,ASCO consulting,New Delhi
38,Kanan,senior technology instructor,NY INST,"Mid Level, Junior Level",Chennai
39,Shashikant Chaudhary,HR Recruiter/HR Excutive,-,3D India Staffing Research & Consulting Co. In...,Aligarh
40,Brad,"Manager, Technical Recruiting",O.C. Tanner (Since Jan-2019),"Junior Level, High Level",Salt Lake City
41,Rutuja Pawar,Technical Recruiter,Demand Matrix (Since Feb-2018),"Python , Php , Qa Automation , Ui , Wordpre",Pune
42,Madhusudhan Sridhar,Erp Implementer,-,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore
43,Ankit Sinha,Head-Analytics,-,Suntech Global (Since Feb-2018),Mumbai
44,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Top Mangement Level, Junior Level",Indore
45,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science , Node.js , Angularjs",Bengaluru / Bangalore
46,Ashwini,"Director, Global Delivery",-,MRP Advisers (Since Oct-2017),MYSORE
47,Balaji Kolli,Co-Founder,-,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad
48,Rajani Nagaraj,HR Manager,WildJasmine,"java , hadoop , r , Machine Learning , spark ,...",Bengaluru / Bangalore
49,ROHIT Kumar,Architect,LNT Private Limited (Since Jul-2017),"Mid Level, High Level",Mumbai

# 8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [25]:
driver=webdriver.Chrome(r"C:\Rajashri\Iternship\Chromdriver\chromedriver.exe")
url = 'https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)

In [26]:
#creating empty list for all the elements
rank=[]
book_names = []
author_names = []
volumes_sold = []
publisher = []
genre = []

#No need for exception handlnig as the data is in table format and all the data points are available to extract.
Rank_obj = driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[1]')
for i in Rank_obj:
    rank.append(i.text)

    #NAME OF BOOK
    
Names_obj = driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]')
for i in Names_obj:
    book_names.append(i.text)

    #AUTHOR NAME
author_obj = driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[3]')
for i in author_obj:
    author_names.append(i.text)

        
    #VOLUME OF BOOKS SOLD
volume_obj = driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[4]')
for i in volume_obj:
    volumes_sold.append(i.text)

    #PUBLISHER NAME
publisher_obj = driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[5]')
for i in publisher_obj:
    publisher.append(i.text)

        
    #GENRE ELEMENT
genre_obj = driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[6]')
for i in genre_obj:
    genre.append(i.text)

In [27]:
#Creating a dictionary of all the elements
dict = {
   'Rank':rank, 'Book name':book_names,'Author name':author_names,'Volumes sold':volumes_sold,
    'Publisher':publisher,'Genre':genre
}
#Dataframe/Table creating of the dictionary
table = pd.DataFrame(dict)
table

,Rank,Book name,Author name,Volumes sold,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [28]:
driver=webdriver.Chrome(r"C:\Rajashri\Iternship\Chromdriver\chromedriver.exe")
url = 'https://www.imdb.com/list/ls095964455/'
driver.get(url)

In [29]:
movies = []
year_span = []
genre = []
run_time = []
ratings = []
votes = []
#MOIVE NAME ELEMENT

movie_name_obj = driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/a')
for i in movie_name_obj:
    movies.append(i.text)

        
    #YEAR SPAN OBJECT

year_span_obj = driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/span[2]')
for i in year_span_obj:
    year_span.append(i.text)

    #GENRE OBJECT

genre_obj = driver.find_elements_by_xpath('//span[@class="genre"]')
for i in genre_obj:
    genre.append(i.text)

        
    #RUNTIME ELEMENT
    
runtime_obj = driver.find_elements_by_xpath('//span[@class="runtime"]')
for i in runtime_obj:
    run_time.append(i.text)

    #RATING OBJECT
    
rating_obj = driver.find_elements_by_xpath('//div[@class="ipl-rating-star small"]/span[2]')
for i in rating_obj:
    ratings.append(i.text)

    #NO OF VOTES OBJECT
       
votes_obj = driver.find_elements_by_xpath('//*[@id="main"]/div/div[3]/div[3]/div/div[2]/p[4]/span[2]')
for i in votes_obj:
    votes.append(i.text)

In [30]:
#creating a dictionary of all the elements
dict = {
    'Movie Name':movies,'Year Span':year_span,'Genre':genre,'Run time':run_time,
    'Rating':ratings,'Votes':votes
}
#data frame creation
table = pd.DataFrame(dict)
table

,Movie Name,Year Span,Genre,Run time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,882,042"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"915,485"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"903,992"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"270,865"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"231,254"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,883"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,756"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"177,245"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"36,871"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"203,427"

# 10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the Show All Dataset page through code.

In [38]:
driver=webdriver.Chrome(r"C:\Rajashri\Iternship\Chromdriver\chromedriver.exe")
url = 'https://archive.ics.uci.edu/'
driver.get(url)
#repository element element object
repository_links = driver.find_elements_by_xpath('//span[@class="normal"]/a')
#al lthe repository element links
for i in repository_links:
    print(i.get_attribute('href'))

https://archive.ics.uci.edu/ml/index.html
http://cml.ics.uci.edu/
https://archive.ics.uci.edu/ml/about.html
https://archive.ics.uci.edu/ml/citation_policy.html
https://archive.ics.uci.edu/ml/donation_policy.html
https://archive.ics.uci.edu/ml/contact.html
http://archive.ics.uci.edu/ml/noteNetflix.txt
https://archive.ics.uci.edu/ml/datasets/Kinship
https://archive.ics.uci.edu/ml/datasets/Synchronous+Machine+Data+Set
https://archive.ics.uci.edu/ml/datasets/Wikipedia+Math+Essentials
https://archive.ics.uci.edu/ml/datasets/Wikipedia+Math+Essentials
https://archive.ics.uci.edu/ml/datasets/Hungarian+Chickenpox+Cases
https://archive.ics.uci.edu/ml/datasets/Myocardial+infarction+complications
https://archive.ics.uci.edu/ml/datasets/Gait+Classification
https://archive.ics.uci.edu/ml/datasets/Codon+usage
https://archive.ics.uci.edu/ml/datasets/in-vehicle+coupon+recommendation
https://archive.ics.uci.edu/ml/datasets/Dry+Bean+Dataset
https://archive.ics.uci.edu/ml/datasets/Intelligent+Media+Accelerometer+and+Gyroscope+%28IM-AccGyro%29+Dataset
https://archive.ics.uci.edu/ml/datasets/AI4I+2020+Predictive+Maintenance+Dataset
https://archive.ics.uci.edu/ml/datasets/Wisesight+Sentiment+Corpus
https://archive.ics.uci.edu/ml/datasets/Iris
https://archive.ics.uci.edu/ml/datasets/Adult
https://archive.ics.uci.edu/ml/datasets/Wine
https://archive.ics.uci.edu/ml/datasets/Wine+Quality
https://archive.ics.uci.edu/ml/datasets/Heart+Disease
https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29
https://archive.ics.uci.edu/ml/datasets/Bank+Marketing
https://archive.ics.uci.edu/ml/datasets/Car+Evaluation
https://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones
https://archive.ics.uci.edu/ml/datasets/Abalone
https://archive.ics.uci.edu/ml/datasets/Forest+Fires
https://archive.ics.uci.edu/ml/datasets/Student+Performance
https://archive.ics.uci.edu/ml/about.html
https://archive.ics.uci.edu/ml/citation_policy.html
https://archive.ics.uci.edu/ml/donation_policy.html
https://archive.ics.uci.edu/ml/contact.html
http://cml.ics.uci.edu/

In [39]:
#Dataset URLS
urls = []
for i in repository_links:
    if(i.get_attribute('href').find('datasets')>0):
        urls.append(i.get_attribute('href'))
urls

['https://archive.ics.uci.edu/ml/datasets/Kinship',
 'https://archive.ics.uci.edu/ml/datasets/Synchronous+Machine+Data+Set',
 'https://archive.ics.uci.edu/ml/datasets/Wikipedia+Math+Essentials',
 'https://archive.ics.uci.edu/ml/datasets/Wikipedia+Math+Essentials',
 'https://archive.ics.uci.edu/ml/datasets/Hungarian+Chickenpox+Cases',
 'https://archive.ics.uci.edu/ml/datasets/Myocardial+infarction+complications',
 'https://archive.ics.uci.edu/ml/datasets/Gait+Classification',
 'https://archive.ics.uci.edu/ml/datasets/Codon+usage',
 'https://archive.ics.uci.edu/ml/datasets/in-vehicle+coupon+recommendation',
 'https://archive.ics.uci.edu/ml/datasets/Dry+Bean+Dataset',
 'https://archive.ics.uci.edu/ml/datasets/Intelligent+Media+Accelerometer+and+Gyroscope+%28IM-AccGyro%29+Dataset',
 'https://archive.ics.uci.edu/ml/datasets/AI4I+2020+Predictive+Maintenance+Dataset',
 'https://archive.ics.uci.edu/ml/datasets/Wisesight+Sentiment+Corpus',
 'https://archive.ics.uci.edu/ml/datasets/Iris',
 'https://archive.ics.uci.edu/ml/datasets/Adult',
 'https://archive.ics.uci.edu/ml/datasets/Wine',
 'https://archive.ics.uci.edu/ml/datasets/Wine+Quality',
 'https://archive.ics.uci.edu/ml/datasets/Heart+Disease',
 'https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29',
 'https://archive.ics.uci.edu/ml/datasets/Bank+Marketing',
 'https://archive.ics.uci.edu/ml/datasets/Car+Evaluation',
 'https://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones',
 'https://archive.ics.uci.edu/ml/datasets/Abalone',
 'https://archive.ics.uci.edu/ml/datasets/Forest+Fires',
 'https://archive.ics.uci.edu/ml/datasets/Student+Performance']

In [40]:
dataset_names = []
dataset_datatypes = []
tasks = []
attribute_types = []
no_instances = []
no_attributes = []
year = []


#Looping through the each dataset urls-> 

for i in urls:
    driver.get(i)
    
    #dataset name
    
    try:
        dataset_name_obj = driver.find_element_by_xpath('//span[@class="heading"]/b')
        dataset_names.append(dataset_name_obj.text)
    except:
        dataset_names.append('-')
       
    #DATA SET DATA TYPES
    try:
        dataset_datatype_obj = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[1]/td[2]/p')
        dataset_datatypes.append(dataset_datatype_obj.text)
    except:
        dataset_datatypes.append('-')
        
    #TASKS  
        
    try:
        dataset_task_obj = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[3]/td[2]/p')
        tasks.append(dataset_task_obj.text)
    except:
        tasks.append('-')
      
    #ATTRIBUTE TYPES
        
    try:
        dataset_attr_type_obj = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[2]/td[2]/p')
        attribute_types.append(dataset_attr_type_obj.text)
    except:
        attribute_types.append('-')
        
   
    #no of instances  
    try:
        dataset_instances_obj = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[1]/td[4]/p')
        no_instances.append(dataset_instances_obj.text)
    except:
        no_instances.append('-')
        
     #no of attributes   
        
    try:
        dataset_attr_obj = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[2]/td[4]/p')
        no_attributes.append(dataset_attr_obj.text)
    except:
        no_attributes.append('-')
    
      
    #year of DATASET
    try:
        year_obj = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[2]/td[6]/p')
        year.append(year_obj.text)
    except:
        year.append('-')

In [41]:
#creating a dictionary of all the elements
dict = {
    'Dataset name': dataset_names, 'Data type':dataset_datatypes,'Task':tasks,
    'Attribute type':attribute_types, 'No of instances':no_instances,
    'No of attribute':no_instances,'Year':year
}

#creating a Table from the dictionary
table = pd.DataFrame(dict)
table

,Dataset name,Data type,Task,Attribute type,No of instances,No of attribute,Year
0,Kinship Data Set,Relational,Relational-Learning,Categorical,104,104,1990-07-01
1,Synchronous Machine Data Set Data Set,Multivariate,Regression,Real,557,557,2021-04-21
2,Wikipedia Math Essentials Data Set,Time-Series,Regression,Real,731,731,2021-04-20
3,Wikipedia Math Essentials Data Set,Time-Series,Regression,Real,731,731,2021-04-20
4,Hungarian Chickenpox Cases Data Set,Time-Series,Regression,Real,521,521,2021-02-17
5,Myocardial infarction complications Data Set,Multivariate,Classification,Real,1700,1700,2020-12-09
6,Gait Classification Data Set,Multivariate,Classification,Real,48,48,2020-10-14
7,Codon usage Data Set,Multivariate,"Classification, Clustering",N/A,13028,13028,2020-10-03
8,in-vehicle coupon recommendation Data Set,Multivariate,Classification,N/A,12684,12684,2020-09-15
9,Dry Bean Dataset Data Set,Multivariate,Classification,"Integer, Real",13611,13611,2020-09-14
10,Intelligent Media Accelerometer and Gyroscope ...,Time-Series,Classification,Real,800,800,2020-09-03
11,AI4I 2020 Predictive Maintenance Dataset Data Set,"Multivariate, Time-Series","Classification, Regression, Causal-Discovery",Real,10000,10000,2020-08-30
12,Wisesight Sentiment Corpus Data Set,"Multivariate, Text",Classification,N/A,26737,26737,2020-08-25
13,Iris Data Set,Multivariate,Classification,Real,150,150,1988-07-01
14,Adult Data Set,Multivariate,Classification,"Categorical, Integer",48842,48842,1996-05-01
15,Wine Data Set,Multivariate,Classification,"Integer, Real",178,178,1991-07-01
16,Wine Quality Data Set,Multivariate,"Classification, Regression",Real,4898,4898,2009-10-07
17,Heart Disease Data Set,Multivariate,Classification,"Categorical, Integer, Real",303,303,1988-07-01
18,Breast Cancer Wisconsin (Diagnostic) Data Set,Multivariate,Classification,Real,569,569,1995-11-01
19,Bank Marketing Data Set,Multivariate,Classification,Real,45211,45211,2012-02-14
20,Car Evaluation Data Set,Multivariate,Classification,Categorical,1728,1728,1997-06-01
21,Human Activity Recognition Using Smartphones D...,"Multivariate, Time-Series","Classification, Clustering",N/A,10299,10299,2012-12-10
22,Abalone Data Set,Multivariate,Classification,"Categorical, Integer, Real",4177,4177,1995-12-01
23,Forest Fires Data Set,Multivariate,Regression,Real,517,517,2008-02-29
24,Student Performance Data Set,Multivariate,"Classification, Regression",Integer,649,649,2014-11-27